<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\Models\User;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $this->call([
            MasterDistributorSeeder::class,
        ]);
        
        if(DB::table('permissions')->count() == 0)
        {
            DB::table('permissions')->insert([
                ['name' => 'dashboard_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'permission_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'permission_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'role_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'role_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'role_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'role_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'country_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'country_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'country_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'country_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'country_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'country_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'country_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'state_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'state_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'state_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'state_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'state_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'state_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'state_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'district_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'district_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'district_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'district_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'district_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'district_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'district_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'city_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'city_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'city_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'city_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'city_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'city_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'city_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'pincode_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'pincode_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'pincode_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'pincode_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'pincode_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'pincode_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'pincode_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'customertype_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'customertype_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'customertype_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'customertype_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'customertype_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'customertype_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'customertype_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'firmtype_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'firmtype_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'firmtype_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'firmtype_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'firmtype_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'firmtype_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'firmtype_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'customer_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'customer_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'customer_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'customer_show', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'customer_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'customer_login', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'customer_active', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'customer_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'customer_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'customer_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'survey_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'survey_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'field_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'field_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'field_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'field_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'distributor_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'distributor_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'distributor_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'distributor_show', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'distributor_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'distributor_active', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'distributor_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'distributor_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'user_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'user_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'user_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'user_show', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'user_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'user_login', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'user_active', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'user_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'user_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'user_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'user_location', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'attendance_report', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'summary_report', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'adherence_report', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'visit_report', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'customers_report', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'daily_visit_report', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'fielda_ctivity_report', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'tour_programme_report', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'monthly_movement_report', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'point_collections_report', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'territory_coverage_report', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'performance_parameter_report', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'mechanics_points_report', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'targetvs_sales_report', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'target_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'target_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'target_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'target_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'category_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'category_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'category_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'category_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'category_active', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'category_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'category_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'category_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'subcategory_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'subcategory_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'subcategory_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'subcategory_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'subcategory_active', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'subcategory_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'subcategory_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'subcategory_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'brand_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'brand_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'brand_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'brand_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'brand_active', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'brand_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'brand_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'brand_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'product_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'product_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'product_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'product_show', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'product_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'product_active', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'product_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'product_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'product_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'max_discount', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'gift_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'gift_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'gift_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'gift_show', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'gift_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'gift_active', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'gift_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'gift_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'gift_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'unit_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'unit_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'unit_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'unit_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'unit_active', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'unit_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'unit_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'unit_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'order_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'order_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'order_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'order_show', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'order_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'order_active', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'order_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'order_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'order_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'purchase_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'purchase_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'purchase_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'purchase_show', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'purchase_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'purchase_active', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'purchase_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'purchase_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'purchase_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'sale_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'sale_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'sale_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'sale_show', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'sale_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'sale_active', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'sale_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'sale_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'sale_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'wallet_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'wallet_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'wallet_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'wallet_show', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'wallet_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'wallet_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'wallet_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'wallet_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'redeemedpoint_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'redeemedpoint_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'redeemedpoint_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'redeemedpoint_show', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'redeemedpoint_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'redeemedpoint_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'redeemedpoint_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'redeemedpoint_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'scheme_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'scheme_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'scheme_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'scheme_show', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'scheme_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'scheme_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'scheme_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'scheme_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'setting_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'setting_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'setting_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'setting_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'setting_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'setting_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'setting_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'status_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'status_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'status_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'status_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'status_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'status_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'status_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'coupon_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'coupon_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'coupon_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'coupon_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'coupon_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'coupon_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'coupon_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'couponprofile_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'couponprofile_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'couponprofile_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'couponprofile_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'beat_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'beat_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'beat_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'beat_show', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'beat_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'beat_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'beat_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'beat_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'beatdetail_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'beatdetail_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'beatdetail_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'beatdetail_show', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'beatdetail_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'beatdetail_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'beatdetail_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'beatdetail_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'attendance_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'attendance_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'attendance_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'attendance_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'attendance_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'attendance_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'attendance_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'checkin_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'checkin_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'checkin_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'checkin_show', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'checkin_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'checkin_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'checkin_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'checkin_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'visitreport_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'visitreport_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'visitreport_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'visitreport_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'visitreport_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'visitreport_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'visitreport_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'visittype_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'visittype_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'visittype_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'visittype_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'visittype_active', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'visittype_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'visittype_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'visittype_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'stock_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'stock_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'stock_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'stock_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'stock_active', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'stock_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'stock_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'stock_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'stockdetails_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'stockdetails_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'stockdetails_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'stockdetails_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'stockdetails_active', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'stockdetails_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'stockdetails_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'stockdetails_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'leads_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'leads_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'leads_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'leads_show', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'leads_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'leads_active', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'leads_staus', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'leads_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'leads_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'leads_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'tasks_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'tasks_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'tasks_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'tasks_show', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'tasks_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'tasks_active', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'tasks_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'tasks_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'tasks_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'payments_access', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'payments_create', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'payments_edit', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'payments_show', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'payments_delete', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'payments_active', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'payments_upload', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'payments_download', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'payments_template', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'branch', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'division', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'designation', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'tours', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
                ['name' => 'city_assigned', 'guard_name' => 'users','created_at' => date('Y-m-d H:i:s'),'updated_at' => date('Y-m-d H:i:s')],
            ]);
        }
        if(DB::table('roles')->count() == 0)
        {
            $permissions = Permission::pluck('name');
            $role = Role::create(['guard_name' => 'users', 'name' => 'superadmin']);
            foreach ($permissions as $key => $permission) {
                $role->givePermissionTo($permission);
            }
            
        }
        if(DB::table('users')->count() == 0)
         {
                $user = User::create([
                         'active' => 'Y',
                         'name' => 'Ajay Dhangar',
                         'first_name' => 'Ajay',
                         'last_name' => 'Dhangar',
                         'mobile' => '9303142046',
                         'email' => 'ajay.dhangar@gmail.com',
                         'gender' => 'Male',
                         'profile_image' => '',
                         'password' => Hash::make('12345678'),
                     ]);
                $role = Role::find(1);
                $user->syncRoles($role);
                $permissions = $user->getPermissionsViaRoles()->pluck('name');
                $user->givePermissionTo($permissions);
         }
    }
}
