<x-app-layout>
<style>
.cf-card{background:#071a3f;border:1px solid #17386d;border-radius:14px;margin-bottom:20px;overflow:hidden}.cf-title{padding:16px 20px;border-bottom:1px solid #17386d;color:#fff;font-size:18px;font-weight:700}.cf-body{padding:20px}.cf label{color:#91a5d1;font-weight:600}.cf .form-control,.cf .select2-selection{min-height:48px!important;border:1px solid #294779!important;border-radius:9px!important;background:#081b42!important;color:#fff!important}.cf .select2-selection__rendered{color:#fff!important;line-height:46px!important}.cf .select2-selection__arrow{height:46px!important}.cf .readonly{background:#10264f!important;color:#a9b6d3!important}.cf textarea{min-height:120px!important}.units{display:flex;gap:18px;align-items:center;height:48px;color:#fff}.cf-submit{background:linear-gradient(90deg,#25c8e9,#3d8df5);border:0;border-radius:10px;padding:13px 28px;font-weight:700}.attach-preview{display:none;max-width:260px;max-height:180px;border-radius:10px;margin-top:12px;object-fit:cover}
</style>
<div class="card mt-0 p-0"><div class="card-header card-header-warning d-flex justify-content-between align-items-center"><h4 class="card-title mb-0">{{$complaints->exists?'Edit Complaint':'New Complaint'}}</h4><a href="{{route('complaints.index')}}" class="btn btn-sm btn-light">Complaints</a></div>
<div class="card-body cf">@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{$complaints->exists?route('complaints.update',$complaints->id):route('complaints.store')}}" enctype="multipart/form-data" id="complaintForm">@csrf @if($complaints->exists)@method('PUT')@endif
<div class="cf-card"><div class="cf-title">Complaint Info</div><div class="cf-body row"><div class="col-md-6"><label>Complaint No.</label><input class="form-control readonly" readonly value="{{$complaints->exists?$complaints->complaint_number:'For eg. '.$exampleComplaintNumber}}"></div><div class="col-md-6"><label>Complaint Date</label><input type="date" name="complaint_date" class="form-control readonly" readonly value="{{old('complaint_date',$complaints->exists?\Carbon\Carbon::parse($complaints->getRawOriginal('complaint_date'))->format('Y-m-d'):now()->toDateString())}}"></div></div></div>
<div class="cf-card"><div class="cf-title">Complaint Received From</div><div class="cf-body row"><div class="col-md-6 mb-3"><label>Dealer Name *</label><select name="dealer_id" id="dealer_id" class="form-control select2" required><option value="">Select dealer</option>@foreach($dealers as $dealer)@php($a=$dealer->customeraddress)<option value="{{$dealer->id}}" data-address="{{collect([$a->address1??null,$a->address2??null,$a->landmark??null,$a->locality??null,$a->zipcode??null])->filter()->implode(', ')}}" data-contact="{{$dealer->mobile?:$dealer->contact_number}}" {{old('dealer_id')==$dealer->id?'selected':''}}>{{$dealer->name?:trim($dealer->first_name.' '.$dealer->last_name)}}</option>@endforeach</select></div><div class="col-md-6 mb-3"><label>Address</label><input id="dealer_address" class="form-control readonly" readonly></div><div class="col-md-6"><label>Contact No.</label><input id="dealer_contact" class="form-control readonly" readonly></div><div class="col-md-6"><label>Alternate Number</label><input name="alternate_number" class="form-control phone" maxlength="10" value="{{old('alternate_number')}}" placeholder="Optional"></div></div></div>
<div class="cf-card"><div class="cf-title">End User</div><div class="cf-body row"><div class="col-md-6"><label>Name</label><input name="end_user_name" class="form-control" maxlength="150" value="{{old('end_user_name')}}"></div><div class="col-md-6"><label>Mobile No.</label><input name="end_user_mobile" class="form-control phone" maxlength="10" value="{{old('end_user_mobile')}}"></div></div></div>
<div class="cf-card"><div class="cf-title">Technician</div><div class="cf-body row"><div class="col-md-6"><label>Mobile No.</label><input name="technician_mobile" class="form-control phone" maxlength="10" value="{{old('technician_mobile')}}"></div></div></div>
<div class="cf-card"><div class="cf-title">Product Details</div><div class="cf-body row"><div class="col-md-6 mb-3"><label>Category *</label><select name="product_category_id" class="form-control select2" required><option value="">Select category</option>@foreach($categories as $category)<option value="{{$category->id}}" {{old('product_category_id')==$category->id?'selected':''}}>{{$category->category_name}}</option>@endforeach</select></div><div class="col-md-3"><label>Size</label><input name="product_size" class="form-control" maxlength="50" value="{{old('product_size')}}" placeholder="e.g. 4"></div><div class="col-md-3"><label>Unit</label><div class="units"><label><input type="radio" name="size_unit" value="MM" {{old('size_unit','MM')==='MM'?'checked':''}}> MM</label><label><input type="radio" name="size_unit" value="Inch" {{old('size_unit')==='Inch'?'checked':''}}> Inch</label></div></div><div class="col-md-6"><label>Batch No. / DOM</label><input name="batch_no_dom" class="form-control" maxlength="100" value="{{old('batch_no_dom')}}"></div></div></div>
<div class="cf-card"><div class="cf-title">Complaint Details</div><div class="cf-body row"><div class="col-md-12 mb-3"><label>Nature of Complaint *</label><textarea name="description" class="form-control" maxlength="5000" required>{{old('description')}}</textarea></div><div class="col-md-6"><label>Complaint Received Through *</label><select name="complaint_received_through_id" class="form-control select2" required><option value="">Select source</option>@foreach($receivedThrough as $source)<option value="{{$source->id}}" {{old('complaint_received_through_id')==$source->id?'selected':''}}>{{$source->display_name?:$source->status_name}}</option>@endforeach</select></div></div></div>
<div class="cf-card"><div class="cf-title">Attachment</div><div class="cf-body"><input type="file" name="attachment" id="attachment" class="form-control" accept="image/*,.pdf"><img id="attachmentPreview" class="attach-preview" alt="Attachment preview"></div></div>
<div class="text-right"><button class="btn cf-submit" type="submit">Submit Complaint</button></div></form></div></div>
<script>$(function(){$('.select2').select2({width:'100%'});@if($complaints->exists)const editData=@json(['dealer_id'=>$complaints->party_name,'alternate_number'=>$complaints->alternate_number?:$complaints->remark,'end_user_name'=>$complaints->end_user_name?:optional($complaints->customer)->customer_name,'end_user_mobile'=>$complaints->end_user_mobile?:optional($complaints->customer)->customer_number,'technician_mobile'=>$complaints->technician_mobile?:$complaints->service_centre_remark,'product_category_id'=>$complaints->form_category_id,'product_size'=>$complaints->product_size?:trim(preg_replace('/\s+(MM|Inch)$/i','',$complaints->specification??'')),'size_unit'=>$complaints->size_unit?:((stripos($complaints->specification??'','inch')!==false)?'Inch':'MM'),'batch_no_dom'=>$complaints->batch_no_dom?:$complaints->product_no,'description'=>$complaints->description,'complaint_received_through_id'=>$complaints->form_received_id]);Object.keys(editData).forEach(function(name){let input=$('[name="'+name+'"]');if(input.is(':radio'))input.filter('[value="'+editData[name]+'"]').prop('checked',true);else input.val(editData[name]);});$('.select2').trigger('change');@endif function dealer(){let o=$('#dealer_id option:selected');$('#dealer_address').val(o.data('address')||'');$('#dealer_contact').val(o.data('contact')||'')}$('#dealer_id').on('change',dealer);dealer();$('.phone').on('input',function(){this.value=this.value.replace(/\D/g,'').slice(0,10)});$('#complaintForm').on('submit',function(e){let bad=false;$('.phone').each(function(){if(this.value&&this.value.length!==10)bad=true});if(bad){e.preventDefault();alert('Mobile numbers must contain exactly 10 digits.')}});$('#attachment').on('change',function(){let f=this.files[0],p=$('#attachmentPreview');if(f&&f.type.startsWith('image/'))p.attr('src',URL.createObjectURL(f)).show();else p.hide()})});</script>
</x-app-layout>
